# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser
import os


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(481, 606)
        Dialog.setStyleSheet("background-color: rgb(150, 87, 255);")
        self.PygameButton = QtWidgets.QPushButton(Dialog)
        self.PygameButton.setGeometry(QtCore.QRect(10, 90, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.PygameButton.setFont(font)
        self.PygameButton.setStyleSheet("background-color: rgb(75, 147, 255);\n"
"")
        self.PygameButton.setObjectName("PygameButton")
        self.DjangoButton = QtWidgets.QPushButton(Dialog)
        self.DjangoButton.setGeometry(QtCore.QRect(320, 230, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.DjangoButton.setFont(font)
        self.DjangoButton.setStyleSheet("background-color: rgb(68, 55, 255);")
        self.DjangoButton.setObjectName("DjangoButton")
        self.Cv2Button = QtWidgets.QPushButton(Dialog)
        self.Cv2Button.setGeometry(QtCore.QRect(10, 380, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Cv2Button.setFont(font)
        self.Cv2Button.setStyleSheet("background-color: rgb(46, 255, 168);")
        self.Cv2Button.setObjectName("Cv2Button")
        self.PyQTButton = QtWidgets.QPushButton(Dialog)
        self.PyQTButton.setGeometry(QtCore.QRect(320, 520, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.PyQTButton.setFont(font)
        self.PyQTButton.setStyleSheet("background-color: rgb(182, 10, 255);")
        self.PyQTButton.setObjectName("PyQTButton")
        self.MyProjects = QtWidgets.QLabel(Dialog)
        self.MyProjects.setGeometry(QtCore.QRect(10, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MyProjects.setFont(font)
        self.MyProjects.setObjectName("MyProjects")
        self.DjangoLabel = QtWidgets.QLabel(Dialog)
        self.DjangoLabel.setGeometry(QtCore.QRect(320, 180, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.DjangoLabel.setFont(font)
        self.DjangoLabel.setObjectName("DjangoLabel")
        self.PygameLabel = QtWidgets.QLabel(Dialog)
        self.PygameLabel.setGeometry(QtCore.QRect(10, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PygameLabel.setFont(font)
        self.PygameLabel.setObjectName("PygameLabel")
        self.Cv2Label = QtWidgets.QLabel(Dialog)
        self.Cv2Label.setGeometry(QtCore.QRect(10, 330, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Cv2Label.setFont(font)
        self.Cv2Label.setObjectName("Cv2Label")
        self.PyQTLabel = QtWidgets.QLabel(Dialog)
        self.PyQTLabel.setGeometry(QtCore.QRect(320, 440, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PyQTLabel.setFont(font)
        self.PyQTLabel.setObjectName("PyQTLabel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 470, 161, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/Снимок.JPG"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(310, 310, 151, 151))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Pictures/Безымянны1й.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 181, 161))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Pictures/Django.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 211, 171))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Pictures/python-pygame-tutorial.png"))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def openPyQt5(self):
        os.system("PyQT.bat ")
    def openPyGame(self):
        os.system("Game.bat ")
    def openDjango(self):
        webbrowser.open('http://127.0.0.1:8000')
        os.system("Django.bat ")
    def openCV2(self):
        os.system("CV2.bat ")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.PygameButton.setText(_translate("Dialog", "Pygame"))
        self.PygameButton.clicked.connect(self.openPyGame)
        self.DjangoButton.setText(_translate("Dialog", "Django"))
        self.DjangoButton.clicked.connect(self.openDjango)
        self.Cv2Button.setText(_translate("Dialog", "CV2"))
        self.PyQTButton.setText(_translate("Dialog", "PyQT5"))
        self.PyQTButton.clicked.connect(self.openPyQt5)
        self.MyProjects.setText(_translate("Dialog", "MyProjects"))
        self.DjangoLabel.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Сайт на Gjango</span></p></body></html>"))
        self.DjangoLabel.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.DjangoLabel.setText(_translate("Dialog", "Сайт на Gjango"))
        self.PygameLabel.setText(_translate("Dialog", "Игра на библиотеке - Pygame"))
        self.Cv2Label.setText(_translate("Dialog", "Поиск улыбки на лице"))
        self.PyQTLabel.setText(_translate("Dialog", "КАЛЬКУЛЯТОР"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    Dialog.setWindowTitle('My Programs')
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
